### ISSUE TITLE
cách tạo dictionary symspell

### ISSUE THREAD

**Issue by batman-do** [vovanphuc/smartmenu#1]
- Mình muốn hỏi cách các bạn tìm các number frequence của từng bigram như thế nào thế 
- Mình cảm ơn các bạn

**Comment by vovanphuc** [comment]
team mình có crawl data corpus về lĩnh vực món ăn sau đó dùng nltk để tạo file bigram bạn nha

**Comment by batman-do** [comment]
> team mình có crawl data corpus về lĩnh vực món ăn sau đó dùng nltk để tạo file bigram bạn nha

mình muốn hỏi về các con số tần suất xuất hiện mình không hiểu lắm lấy những con số ở đâu, cảm ơn bạn đã trả lời mình

**Comment by vovanphuc** [comment]
bạn dùng nltk thì nó tạo ra được luôn các số lần xuất hiện ấy

**Comment by batman-do** [comment]
> bạn dùng nltk thì nó tạo ra được luôn các số lần xuất hiện ấy

oke bạn, cảm ơn bạn nhé
