### ISSUE TITLE
Huấn luyện

### ISSUE THREAD

**Issue by nhathoang0110** [vovanphuc/smartmenu#2]
Hi bạn,
Mình muốn hỏi bạn finetune mô hình PPOCR3 phần detect sử dụng mô hình gì ?
Và với phần recognition tiếng Việt thì việc huấn luyện bọn paddle nó có tốt hơn VietOCR không?

**Comment by vovanphuc** [comment]
Chào bạn,
Phần detect mình sử dụng DBNet của PPOCRv3,
Phần recog thì mình không benchmark với VietOCR nên không chắc là mô hình nào tốt hơn, do bài toán yêu cầu tối ưu về chạy trên cpu nên mình nghĩ tốc độ infer của PPOCRv3 student nhanh hơn VietOCR.

**Comment by nhathoang0110** [comment]
Cho mình hỏi phần huấn luyện PPOCRv3 bạn huấn luyện riêng phần sử dụng config DBNet của nó hay huấn luyện sử dụng config DistillationModel của ppocrv3.  
Phần recog tiếng việt bạn sử dụng model nào của paddlel vậy ?
Cuối cùng là b có thể cho mình xin file config và model inference paddle format thay vì onnx được không?
Cảm ơn b

**Comment by vovanphuc** [comment]
detect mình sử dụng config DistillationModel bạn nha,
recog thì mình sử dụng model SVTR,
do mình có implement thêm 1 vài trick để tối ưu cho tiếng việt nên có share config hay model paddle thì cũng không load lên bằng paddleocr được nha bạn, bởi vậy mình chỉ share được onnx, bạn thông cảm.

**Comment by nhathoang0110** [comment]
ok cảm ơn bạn nhé
